# Generated by Django 2.2.7 on 2019-11-30 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(verbose_name='Дата создания')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('TIN', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'Учредитель',
                'verbose_name_plural': 'Учредитель',
                'db_table': 'founder',
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(verbose_name='Дата создания')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('TIN', models.CharField(blank=True, max_length=12, verbose_name='ИНН учреждения')),
                ('founder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UrbanTech.Founder', verbose_name='Учредитель')),
            ],
            options={
                'verbose_name': 'Учреждение',
                'verbose_name_plural': 'Учреждение',
                'db_table': 'institute',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(verbose_name='Дата создания')),
                ('type', models.CharField(max_length=255, verbose_name='Тип документа')),
                ('number', models.CharField(max_length=255, verbose_name='Номер')),
                ('creation_date', models.DateTimeField(verbose_name='Дата создания')),
                ('approval_date', models.DateTimeField(verbose_name='Дата утверждения')),
                ('instatute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UrbanTech.Institute', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Документы',
                'verbose_name_plural': 'Документы',
                'db_table': 'documents',
            },
        ),
    ]
