# Generated by Django 2.1.7 on 2019-11-30 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(verbose_name='Дата создания')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('parent_process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hackathon.BaseProcess', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Шаблон процесса',
                'verbose_name_plural': 'Шаблон процесса',
                'db_table': 'base_process',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(verbose_name='Дата создания')),
                ('number', models.CharField(max_length=255, verbose_name='Номер')),
                ('creation_date', models.DateTimeField(verbose_name='Дата создания')),
                ('approval_date', models.DateTimeField(verbose_name='Дата утверждения')),
            ],
            options={
                'verbose_name': 'Документы',
                'verbose_name_plural': 'Документы',
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(verbose_name='Дата создания')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Типы документов',
                'verbose_name_plural': 'Типы документов',
                'db_table': 'document_types',
            },
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(verbose_name='Дата создания')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('TIN', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'Учредитель',
                'verbose_name_plural': 'Учредитель',
                'db_table': 'founder',
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(verbose_name='Дата создания')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('TIN', models.CharField(blank=True, max_length=12, verbose_name='ИНН учреждения')),
                ('institute_type', models.CharField(max_length=255)),
                ('founder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hackathon.Founder', verbose_name='Учредитель')),
            ],
            options={
                'verbose_name': 'Учреждение',
                'verbose_name_plural': 'Учреждение',
                'db_table': 'institute',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(verbose_name='Дата создания')),
                ('expiration_date', models.DateField()),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hackathon.DocumentTypes', verbose_name='Тип документа')),
                ('from_institute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institute_from', to='hackathon.Institute', verbose_name='Отправитель')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hackathon.BaseProcess')),
                ('to_institute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institute_to', to='hackathon.Institute', verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Процесс',
                'verbose_name_plural': 'Процесс',
                'db_table': 'process',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hackathon.Institute', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hackathon.DocumentTypes', verbose_name='Тип документа'),
        ),
    ]
