# Generated by Django 2.1.7 on 2019-11-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_auto_20191130_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseprocess',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='document',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата утверждения'),
        ),
        migrations.AlterField(
            model_name='document',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='documenttypes',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='process',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='userinstitutes',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
