# Generated by Django 2.1.7 on 2019-12-01 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackathon', '0005_auto_20191130_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinstitutes',
            options={'verbose_name': 'Организации пользователя', 'verbose_name_plural': 'Организации пользователя'},
        ),
        migrations.RemoveField(
            model_name='userinstitutes',
            name='TIN',
        ),
        migrations.AddField(
            model_name='userinstitutes',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
