# Generated by Django 2.1.7 on 2019-12-01 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0008_auto_20191201_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institute',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AddField(
            model_name='documenttypes',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание типа документа'),
        ),
        migrations.AddField(
            model_name='process',
            name='law_base',
            field=models.TextField(default='', verbose_name='Законное основание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='institute',
            name='founder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hackathon.Institute', verbose_name='Родительское ведомство'),
        ),
        migrations.RemoveField(
            model_name='process',
            name='document_type',
        ),
        migrations.AddField(
            model_name='process',
            name='document_type',
            field=models.ManyToManyField(to='hackathon.DocumentTypes', verbose_name='Тип документа'),
        ),
    ]
