# Generated by Django 2.1.7 on 2019-12-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0010_AddDescForProcess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='description',
        ),
        migrations.AddField(
            model_name='baseprocess',
            name='description',
            field=models.TextField(default='', null=True, verbose_name='Описание процесса'),
        ),
    ]
