# Generated by Django 2.2.7 on 2019-11-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_InitDocuments'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInstitutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(verbose_name='Дата создания')),
                ('TIN', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН')),
                ('institutes', models.ManyToManyField(to='hackathon.Institute', verbose_name='Доступные организации')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users_institutes',
            },
        ),
    ]
