# Generated by Django 2.1.7 on 2019-11-30 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_userinstitutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseprocess',
            name='parent_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hackathon.BaseProcess', verbose_name='Родитель'),
        ),
    ]
