# Generated by Django 2.1.7 on 2019-12-01 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0007_auto_20191201_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('start_date', models.DateField(default=None, null=True)),
                ('expiration_date', models.DateField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'Периоды',
                'verbose_name_plural': 'Периоды',
                'db_table': 'periods',
            },
        ),
        migrations.AddField(
            model_name='process',
            name='start_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='expiration_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='period',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hackathon.Period', verbose_name='Период планирования'),
        ),
    ]
