# Generated by Django 2.1.7 on 2019-12-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0013_AddDescInOrganiization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseprocess',
            options={'verbose_name': 'Шаблон процесса', 'verbose_name_plural': 'Шаблоны процесса'},
        ),
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name': 'Процесс', 'verbose_name_plural': 'Процесы'},
        ),
        migrations.AddField(
            model_name='institute',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание учреждения'),
        ),
    ]
