# Generated by Django 2.1.7 on 2019-12-01 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0014_AddInstituteDesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='to_institute',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_institute_to', to='hackathon.Institute', verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_type',
            field=models.CharField(choices=[('BUDGET_INSTITUTE', 'Бюджетная организация'), ('AUTONOMOUS_INSTITUTE', 'Автономная организация'), ('PUBLIC_INSTITUTE', 'Казенное учреждение'), ('GOVERNMENT_INSTITUTE', 'Государственное унитарное предприятие')], max_length=255),
        ),
    ]
