# Generated by Django 2.1.7 on 2019-12-01 19:01

import django.core.files.storage
from django.db import migrations, models
import hackathon.models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0016_hackathon'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttypes',
            name='template_file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/upload/', location='C:\\development\\hackathon\\budgetVision\\hackathon\\upload'), upload_to=hackathon.models.upload_to_path, verbose_name='Шаблон документа'),
        ),
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.CharField(blank=True, choices=[('DONE', 'Сделано'), ('OVERDUE', 'Просрочены'), ('IN_PROCESS', 'Нужно сделать')], default='IN_PROCESS', max_length=255, null=True),
        ),
    ]
